### ISSUE TITLE
value error in num_samples=0

### ISSUE THREAD

**Issue by atanuGuin** [echonet/dynamic#19]
I am getting value error in num_samples in each execution. Although I have downloaded all the avi files and 2 csv files in a4c-video-dir, still I am getting this error? 

(my_syft_env) root@XXXXXX:/workspace/xxx/yyy/dynamic# cmd="import echonet; echonet.utils.segmentation.run(modelname=\"deeplabv3_resnet50\",
                                                    save_segmentation=True,
                                                    pretrained=False)"
(my_syft_env) root@XXXXXX:/workspace/xxx/yyy/dynamic# python3 -c "${cmd}"
namespace(DATA_DIR='/workspace/xxx/yyy/dynamic/a4c-video-dir/', FILENAME='echonet.cfg')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/workspace/xxx/yyy/dynamic/echonet/utils/segmentation.py", line 101, in run
    mean, std = echonet.utils.get_mean_and_std(echonet.datasets.Echo(split="train"))
  File "/workspace/xxx/yyy/dynamic/echonet/utils/__init__.py", line 103, in get_mean_and_std
    dataloader = torch.utils.data.DataLoader(
  File "/root/miniconda3/envs/my_syft_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 262, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore
  File "/root/miniconda3/envs/my_syft_env/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 103, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

Any leads would be helpful.
Thanks in advance.

**Comment by douyang** [comment]
The most recent FileList.csv had the split in all caps, and the check of which split each video was in was case sensitive. This has been updated. Please repull and see if this fixes your error.
