### ISSUE TITLE
Some cases with strange masks

### ISSUE THREAD

**Issue by linhlpv** [echonet/dynamic#20]
Hi, thank for your work!
I have worked with the EchoNet-Dynamic dataset and I found some cases that have strange masks. 
Some examples are 
![image](https://user-images.githubusercontent.com/33130456/106164009-1f314280-61bc-11eb-8ab7-5f548fc85cd1.png)
![image](https://user-images.githubusercontent.com/33130456/106164035-26585080-61bc-11eb-9d10-cc5d3dfc1dbd.png)
![image](https://user-images.githubusercontent.com/33130456/106164057-2b1d0480-61bc-11eb-9d7a-00b3c5167ee4.png)
![image](https://user-images.githubusercontent.com/33130456/106164087-340dd600-61bc-11eb-9b51-bd2f4ac8a535.png)
And I will put the list filenames that have strange masks in 
[list_files_with_strange_masks.zip](https://github.com/echonet/dynamic/files/5888459/list_files_with_strange_masks.zip)
Could you check these files. 
Thank you so much!

**Comment by milktea-1** [comment]
hello,i wonder that hoe do you run this cmd.
cmd="import echonet; echonet.utils.segmentation.run(modelname=\"deeplabv3_resnet50\",
                                                    save_segmentation=True,
                                                    pretrained=False)"
python3 -c "${cmd}"
everytime i run it i receive this question 
``   run(modelname="deeplabv3_resnet50",save_segmentation = True,pretrained = False)
  File "D:/心脏/dynamic-master/echonet/utils/segmentation.py", line 101, in run
    mean, std = echonet.utils.get_mean_and_std(echonet.datasets.Echo(split="train"))
  File "D:\心脏\dynamic-master\echonet\utils\__init__.py", line 104, in get_mean_and_std
    dataset, batch_size=batch_size, num_workers=num_workers, shuffle=True)
  File "F:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 802, in __init__
    sampler = RandomSampler(dataset)
  File "F:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\sampler.py", line 64, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integeral value, but got num_samples=0

thank you so much

**Comment by linhlpv** [comment]
Hi @milktea-1,
Do you have the Echonet Dataset?
If you have all of this, you should check the name of the file in two file FileList.csv and VolumeTracings.csv is not the same.
Your erorr could be that the Echodataset did not contain any data and the dataloader can do anything?
I recommend you check the code of the dataset? It's have some  bug about the name of video files.

**Comment by milktea-1** [comment]
thanks for your answer ,i checked my file , i placed them in  the utils foloder,you can see the follow picture,

![问题](https://user-images.githubusercontent.com/40375885/106259789-a46b3480-625a-11eb-81c8-5928cdbc9440.PNG)

and the Videos dataset has all the videos that the author offered.

**Comment by linhlpv** [comment]
Yeah.
I mean the code of Echodataset has some bugs. The bugs are about the filename in two csv file. So when you use echonet.dataset.Echo(), your dataset would not load any videos.

**Comment by linhlpv** [comment]
I have fixed this bug. I could up this code early so u can fix this

**Comment by linhlpv** [comment]
run this code for fix the name file in FileList.csv. U should change the path to your FileList path
`import numpy as np
import pandas as pd
import os

file_list_df = pd.read_csv('/content/EchoNet-Dynamic/FileList.csv')
file_list_df['FileName'] = file_list_df['FileName'].apply(lambda x: x+'.avi')
file_list_df.to_csv('/content/EchoNet-Dynamic/FileList.csv', index=False)`

**Comment by linhlpv** [comment]
after that, I have write some modification in echonet.datasets.Echo
You should copy this code below and replace author code by it
```
"""EchoNet-Dynamic Dataset."""

import pathlib
import os
import collections

import numpy as np
import skimage.draw
import torch.utils.data
import echonet


class Echo(torch.utils.data.Dataset):
    """EchoNet-Dynamic Dataset.
    Args:
        root (string): Root directory of dataset (defaults to `echonet.config.DATA_DIR`)
        split (string): One of {"train", "val", "test", "external_test"}
        target_type (string or list, optional): Type of target to use,
            ``Filename'', ``EF'', ``EDV'', ``ESV'', ``LargeIndex'',
            ``SmallIndex'', ``LargeFrame'', ``SmallFrame'', ``LargeTrace'',
            or ``SmallTrace''
            Can also be a list to output a tuple with all specified target types.
            The targets represent:
                ``Filename'' (string): filename of video
                ``EF'' (float): ejection fraction
                ``EDV'' (float): end-diastolic volume
                ``ESV'' (float): end-systolic volume
                ``LargeIndex'' (int): index of large (diastolic) frame in video
                ``SmallIndex'' (int): index of small (systolic) frame in video
                ``LargeFrame'' (np.array shape=(3, height, width)): normalized large (diastolic) frame
                ``SmallFrame'' (np.array shape=(3, height, width)): normalized small (systolic) frame
                ``LargeTrace'' (np.array shape=(height, width)): left ventricle large (diastolic) segmentation
                    value of 0 indicates pixel is outside left ventricle
                             1 indicates pixel is inside left ventricle
                ``SmallTrace'' (np.array shape=(height, width)): left ventricle small (systolic) segmentation
                    value of 0 indicates pixel is outside left ventricle
                             1 indicates pixel is inside left ventricle
            Defaults to ``EF''.
        mean (int, float, or np.array shape=(3,), optional): means for all (if scalar) or each (if np.array) channel.
            Used for normalizing the video. Defaults to 0 (video is not shifted).
        std (int, float, or np.array shape=(3,), optional): standard deviation for all (if scalar) or each (if np.array) channel.
            Used for normalizing the video. Defaults to 0 (video is not scaled).
        length (int or None, optional): Number of frames to clip from video. If ``None'', longest possible clip is returned.
            Defaults to 16.
        period (int, optional): Sampling period for taking a clip from the video (i.e. every ``period''-th frame is taken)
            Defaults to 2.
        max_length (int or None, optional): Maximum number of frames to clip from video (main use is for shortening excessively
            long videos when ``length'' is set to None). If ``None'', shortening is not applied to any video.
            Defaults to 250.
        clips (int, optional): Number of clips to sample. Main use is for test-time augmentation with random clips.
            Defaults to 1.
        pad (int or None, optional): Number of pixels to pad all frames on each side (used as augmentation).
            and a window of the original size is taken. If ``None'', no padding occurs.
            Defaults to ``None''.
        noise (float or None, optional): Fraction of pixels to black out as simulated noise. If ``None'', no simulated noise is added.
            Defaults to ``None''.
        target_transform (callable, optional): A function/transform that takes in the target and transforms it.
        external_test_location (string): Path to videos to use for external testing.
    """

    def __init__(self, root=None,
                 split="train", target_type="EF",
                 mean=0., std=1.,
                 length=16, period=2,
                 max_length=250,
                 clips=1,
                 pad=None,
                 noise=None,
                 target_transform=None,
                 external_test_location=None):

        if root is None:
            root = echonet.config.DATA_DIR

        self.folder = pathlib.Path(root)
        self.split = split
        if not isinstance(target_type, list):
            target_type = [target_type]
        self.target_type = target_type
        self.mean = mean
        self.std = std
        self.length = length
        self.max_length = max_length
        self.period = period
        self.clips = clips
        self.pad = pad
        self.noise = noise
        self.target_transform = target_transform
        self.external_test_location = external_test_location

        self.fnames, self.outcome = [], []

        if split == "external_test":
            self.fnames = sorted(os.listdir(self.external_test_location))
        else:
            with open(self.folder / "FileList.csv") as f:
                self.header = f.readline().strip().split(",")
                filenameIndex = self.header.index("FileName")
                splitIndex = self.header.index("Split")

                for line in f:
                    lineSplit = line.strip().split(',')

                    fileName = lineSplit[filenameIndex]
                    fileMode = lineSplit[splitIndex].lower()

                    if split in ["all", fileMode] and os.path.exists(self.folder / "Videos" / fileName):
                        self.fnames.append(fileName)
                        self.outcome.append(lineSplit)

            self.frames = collections.defaultdict(list)
            self.trace = collections.defaultdict(_defaultdict_of_lists)

            with open(self.folder / "VolumeTracings.csv") as f:
                header = f.readline().strip().split(",")
                assert header == ["FileName", "X1", "Y1", "X2", "Y2", "Frame"]

                for line in f:
                    filename, x1, y1, x2, y2, frame = line.strip().split(',')
                    x1 = float(x1)
                    y1 = float(y1)
                    x2 = float(x2)
                    y2 = float(y2)
                    frame = int(frame)
                    if frame not in self.trace[filename]:
                        self.frames[filename].append(frame)
                    self.trace[filename][frame].append((x1, y1, x2, y2))
            for filename in self.frames:
                for frame in self.frames[filename]:
                    self.trace[filename][frame] = np.array(self.trace[filename][frame])

            keep = [len(self.frames[f]) >= 2 for f in self.fnames]
            self.fnames = [f for (f, k) in zip(self.fnames, keep) if k]
            self.outcome = [f for (f, k) in zip(self.outcome, keep) if k]

    def __getitem__(self, index):
        # Find filename of video
        if self.split == "external_test":
            video = os.path.join(self.external_test_location, self.fnames[index])
        elif self.split == "clinical_test":
            video = os.path.join(self.folder, "ProcessedStrainStudyA4c", self.fnames[index])
        else:
            video = os.path.join(self.folder, "Videos", self.fnames[index])

        # Load video into np.array
        video = echonet.utils.loadvideo(video).astype(np.float32)

        # Add simulated noise (black out random pixels)
        # 0 represents black at this point (video has not been normalized yet)
        if self.noise is not None:
            n = video.shape[1] * video.shape[2] * video.shape[3]
            ind = np.random.choice(n, round(self.noise * n), replace=False)
            f = ind % video.shape[1]
            ind //= video.shape[1]
            i = ind % video.shape[2]
            ind //= video.shape[2]
            j = ind
            video[:, f, i, j] = 0

        # Apply normalization
        if isinstance(self.mean, (float, int)):
            video -= self.mean
        else:
            video -= self.mean.reshape(3, 1, 1, 1)

        if isinstance(self.std, (float, int)):
            video /= self.std
        else:
            video /= self.std.reshape(3, 1, 1, 1)

        # Set number of frames
        c, f, h, w = video.shape
        if self.length is None:
            # Take as many frames as possible
            length = f // self.period
        else:
            # Take specified number of frames
            length = self.length

        if self.max_length is not None:
            # Shorten videos to max_length
            length = min(length, self.max_length)

        if f < length * self.period:
            # Pad video with frames filled with zeros if too short
            # 0 represents the mean color (dark grey), since this is after normalization
            video = np.concatenate((video, np.zeros((c, length * self.period - f, h, w), video.dtype)), axis=1)
            c, f, h, w = video.shape  # pylint: disable=E0633

        if self.clips == "all":
            # Take all possible clips of desired length
            start = np.arange(f - (length - 1) * self.period)
        else:
            # Take random clips from video
            start = np.random.choice(f - (length - 1) * self.period, self.clips)
            

        # Gather targets
        target = []
        for t in self.target_type:
            key = self.fnames[index]
            if t == "Filename":
                target.append(self.fnames[index])
            elif t == "LargeIndex":
                # Traces are sorted by cross-sectional area
                # Largest (diastolic) frame is last
                target.append(np.int(self.frames[key][-1]))
            elif t == "SmallIndex":
                # Largest (diastolic) frame is first
                target.append(np.int(self.frames[key][0]))
            elif t == "LargeFrame":
                target.append(video[:, self.frames[key][-1], :, :])
            elif t == "SmallFrame":
                target.append(video[:, self.frames[key][0], :, :])
            elif t in ["LargeTrace", "SmallTrace"]:
                if t == "LargeTrace":
                    t = self.trace[key][self.frames[key][-1]]
                else:
                    t = self.trace[key][self.frames[key][0]]
                x1, y1, x2, y2 = t[:, 0], t[:, 1], t[:, 2], t[:, 3]
                x = np.concatenate((x1[1:], np.flip(x2[1:])))
                y = np.concatenate((y1[1:], np.flip(y2[1:])))

                r, c = skimage.draw.polygon(np.rint(y).astype(np.int), np.rint(x).astype(np.int), (video.shape[2], video.shape[3]))
                mask = np.zeros((video.shape[2], video.shape[3]), np.float32)
                mask[r, c] = 1
                target.append(mask)
            else:
                if self.split == "clinical_test" or self.split == "external_test":
                    target.append(np.float32(0))
                else:
                    target.append(np.float32(self.outcome[index][self.header.index(t)]))

        if target != []:
            target = tuple(target) if len(target) > 1 else target[0]
            if self.target_transform is not None:
                target = self.target_transform(target)

        # Select random clips
        video = tuple(video[:, s + self.period * np.arange(length), :, :] for s in start)
        if self.clips == 1:
            video = video[0]
        else:
            video = np.stack(video)

        if self.pad is not None:
            # Add padding of zeros (mean color of videos)
            # Crop of original size is taken out
            # (Used as augmentation)
            c, l, h, w = video.shape
            temp = np.zeros((c, l, h + 2 * self.pad, w + 2 * self.pad), dtype=video.dtype)
            temp[:, :, self.pad:-self.pad, self.pad:-self.pad] = video  # pylint: disable=E1130
            i, j = np.random.randint(0, 2 * self.pad, 2)
            video = temp[:, :, i:(i + h), j:(j + w)]

        return video, target

    def __len__(self):
        return len(self.fnames)


def _defaultdict_of_lists():
    """Returns a defaultdict of lists.
    This is used to avoid issues with Windows (if this function is anonymous,
    the Echo dataset cannot be used in a dataloader).
    """

    return collections.defaultdict(list)
```

**Comment by linhlpv** [comment]
After done all, let uninstall echonet and reinstall it!

**Comment by milktea-1** [comment]
Thank you very much,i will try it  in the day, i am  troubled in it  for a long time until i saw your question,you are my savior!

**Comment by linhlpv** [comment]
Oki, u re wellcome.

**Comment by convnet-ai** [comment]
@linhlpv I tried your solution and it didn't work for me. Can you please help. I downloaded the dataset and created the  echonet/dynamic/a4c-video-dir folder. I put FileList.csv, VolumeTracings.csv and all the videos in it (question: should the videos be under their own Videos folder?). I then ran your script to add .avi the all the files in FileList.csv (the videos in VolumeTracings.csv have already all .avi extensions). Finally I ran the code and error was:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Echonet/dynamic/echonet/utils/segmentation.py", line 101, in run
    mean, std = echonet.utils.get_mean_and_std(echonet.datasets.Echo(split="train"))
  File "/Echonet/dynamic/echonet/utils/__init__.py", line 103, in get_mean_and_std
    dataloader = torch.utils.data.DataLoader(
  File "/Library/Python/3.9/lib/python/site-packages/torch/utils/data/dataloader.py", line 262, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore
  File "/Library/Python/3.9/lib/python/site-packages/torch/utils/data/sampler.py", line 108, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

I have been trying to make it work for hours with no luck. Any help please?

**Comment by linhlpv** [comment]
Hi @convnet-ai , sorry about my late, I have finished my Tet holiday.
Your problem seems like the Dataset have no data. It's maybe caused by the root path param in the class Echo was wrong. You can change it in the config.py or you can pass the root params when you create the Echo dataset

**Comment by milktea-1** [comment]
@linhlpv happy new year ,sorry to trouble you again,i wonder that did you run the video.py,i run 45 epochs succuessfully but receive this error
`RuntimeError: CUDA out of memory. Tried to allocate 5.38 GiB (GPU 0; 23.70 GiB total capacity; 11.14 GiB already allocated; 2.90 GiB free; 14.29 GiB reserved in total by PyTorch)`。
i run it using NVIDIA RTX3090 (24g) pytorch 1.7 。can you give me some help and what's your environment? Thank you very much

**Comment by douyang** [comment]
The most recent FileList.csv had the split in all caps, and the check of which split each video was in was case sensitive. This has been updated. Please repull and see if this fixes your error where num_samples=0 (it looks for a split that does not exist). 

There are a few files with multiple masks, please exclude those or parse them independently.

**Comment by convnet-ai** [comment]
> Hi @convnet-ai , sorry about my late, I have finished my Tet holiday.
> Your problem seems like the Dataset have no data. It's maybe caused by the root path param in the class Echo was wrong. You can change it in the config.py or you can pass the root params when you create the Echo dataset

Sorry for the delay and thanks for your help. I am still struggling to make it work all the way. It stops after 45 epochs with an out of CUDA memory issue. It is too bad that the original authors didn't bother to make or verify that it works
