### ISSUE TITLE
Ventricle Segmentation Exits With Error and Doesn't Generate Videos

### ISSUE THREAD

**Issue by LitMSCTBB** [echonet/dynamic#34]
First of all, thanks for this amazing software. I'm having some trouble running your code.

I ran `echonet segmentation --save_video`  and waited for the epochs to run. In the middle of the third epoch, the program just exits with the following error:
```
Traceback (most recent call last):
  File "C:\Users\akash\AppData\Local\Programs\Python\Python39\Scripts\echonet-script.py", line 33, in <module>
    sys.exit(load_entry_point('echonet==1.0.0', 'console_scripts', 'echonet'))
  File "C:\Users\akash\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1137, in _call__
    return self.main(*args, **kwargs)
  File "C:\Users\akash\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1862, in main
    rv = self.invoke(ctx)
  File "C:\Users\akash\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\akash\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\akash\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 763, in invoke
    return _callback(*args, **kwargs)
  File "C:\Users\akash\AppData\Local\Programs\Python\Python39\lib\site-packages\echonet-1.0.0- 
    py3.9.egglechonet\utils\segmentation.py", line 175, in run
  File "C:\Users\akash\AppData\Local\Programs\Python\Python39\lib\site-packages\echonet-1.0.0-py3.9.egglechonet\utils\segmentation.py", line 432, in run_epoch
  File "C:\Users\akash\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\_tensor.py", line 255, in backward
    torch.autograd. backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "C:\Users\akash\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\autograd\__init__.py", line 147, in backward
    Variable._execution_engine.run_backward
RuntimeError: could not create a primitive
```

The error is similar to the one presented <a href="https://discuss.pytorch.org/t/an-error-on-loss-backward-runtimeerror-could-not-create-a-primitive/117840/3" target="_blank">here</a>. However I'm not able to muster any solution from what's in that thread. Has anyone run into this error for echonet and can give some advice?

I'm running 64-bit Python on Windows 10 with 16 GB RAM.

**Comment by LitMSCTBB** [comment]
Reviving this issue after switching to a Google Cloud Platform VM running Debian 10, with 16 GB of memory and 20 GB of disk space. `echonet segmentation --save_video` no longer results in the error displayed above anymore, but still no videos are present in the output directory.

Additionally, when running `echonet video`, the process just prints "Killed" and exits.

**Comment by bryanhe** [comment]
For the initial issue, I suspect that there is some sort of issue with the Pytorch installation (perhaps a mismatch with the CUDA version).

For the issue with code being killed, this is likely due to a shortage of memory (GCP will kill jobs that exceed memory constraints). You can reduce the batch size or increase the memory allocation.
