### ISSUE TITLE
InitializationNotebook.ipynb

### ISSUE THREAD

**Issue by albertohurt92** [echonet/dynamic#67]
Inside the script, the command echonet.utils.get_mean_and_std(ds, num_workers=2) gives me an error, this is what it tells me
Note: I don’t have CUDA only CPU

runfile('C:/Users/Alberto/Sin título5.py', wdir='C:/Users/Alberto')
The weights are at D:\Echonet\Weights
Segmentation Weights already present
EF Weights already present
loading weights from  D:\Echonet\Weights\r2plus1d_18_32_2_pretrained
cuda is not available, cpu weights
EXTERNAL_TEST ['0X101026B90DAE7E95.avi']
  0%|          | 0/1 [00:05<?, ?it/s]
Traceback (most recent call last):

  File "C:\Users\Alberto\AppData\Roaming\Python\Python39\site-packages\torch\utils\data\dataloader.py", line 986, in _try_get_data
    data = self._data_queue.get(timeout=timeout)

  File "C:\Program Files\Python39\lib\multiprocessing\queues.py", line 114, in get
    raise Empty

Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "C:\Users\Alberto\AppData\Local\Temp\ipykernel_8536\825686444.py", line 1, in <cell line: 1>
    runfile('C:/Users/Alberto/Sin título5.py', wdir='C:/Users/Alberto')

  File "C:\Users\Alberto\AppData\Roaming\Python\Python39\site-packages\debugpy\_vendored\pydevd\_pydev_bundle\pydev_umd.py", line 175, in runfile
    execfile(filename, namespace)

  File "C:\Users\Alberto\AppData\Roaming\Python\Python39\site-packages\debugpy\_vendored\pydevd\_pydev_bundle\_pydev_execfile.py", line 25, in execfile
    exec(compile(contents + "\n", file, 'exec'), glob, loc)

  File "C:/Users/Alberto/Sin título5.py", line 97, in <module>
    mean, std = echonet.utils.get_mean_and_std(ds, num_workers=2)

  File "c:\users\alberto\src\echonet\echonet\utils\__init__.py", line 110, in get_mean_and_std
    for (x, *_) in tqdm.tqdm(dataloader):

  File "C:\Users\Alberto\AppData\Roaming\Python\Python39\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:

  File "C:\Users\Alberto\AppData\Roaming\Python\Python39\site-packages\torch\utils\data\dataloader.py", line 517, in __next__
    data = self._next_data()

  File "C:\Users\Alberto\AppData\Roaming\Python\Python39\site-packages\torch\utils\data\dataloader.py", line 1182, in _next_data
    idx, data = self._get_data()

  File "C:\Users\Alberto\AppData\Roaming\Python\Python39\site-packages\torch\utils\data\dataloader.py", line 1148, in _get_data
    success, data = self._try_get_data()

  File "C:\Users\Alberto\AppData\Roaming\Python\Python39\site-packages\torch\utils\data\dataloader.py", line 999, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e

RuntimeError: DataLoader worker (pid(s) 6784, 1192) exited unexpectedly

**Comment by LitMSCTBB** [comment]
Try 0 workers and a smaller batch size?

**Comment by fiooonna** [comment]
got the same error, does not work even if setting to 0 workers.

**Comment by fiooonna** [comment]
Make sure you have resized the videos before inputting them into the model. I got the same error and resizing them to 112X112 fixed it.
can use the notebook provided by [nakamotoo](https://github.com/nakamotoo/echo-3D-sample/commits?author=nakamotoo)
